- name: "Pull web-ui repo"
  git:
    repo:  https://github.com/kubevirt/web-ui.git
    dest:  "{{ go_path }}/src/github.com/kubevirt/web-ui"
    refspec: "{{ web_ui_refspec }}"
    version: "master"
    force: true

- name: "Pull console repo"
  git:
    repo:  https://github.com/openshift/console
    dest:  "{{ go_path }}/src/github.com/openshift/console"
    refspec: "{{ console_refspec }}"
    version: "master"
    force: true

- name: "Build web-ui"
  command:
    ./build.sh
  args:
    chdir: "{{ go_path }}/src/github.com/kubevirt/web-ui"

- name: "Open iptables 9000/tcp for web-ui"
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 9000
    jump: ACCEPT 
    rule_num: 5
  become: yes

- name: "Start web-ui"
  shell: |
   # TODO(dtrainor): see if there's a better way of running this with individual tasks.  Probably need
   # to see how 'oc login' token is stored, and then used with subsequent Ansible tasks
   # TODO(dtrainor): find a better way to start this in the background; using nohup isn't great but 
   # suitable right now as this is effectively an ephemeral service as of right now
    export BRIDGE_BASE_ADDRESS="http://$(hostname):9000"
    export BRIDGE_LISTEN="http://$(hostname):9000"
    export KUBECONFIG="{{ dev_scripts_dir }}/ocp/auth/kubeconfig"


    oc login -u kubeadmin -p $(cat {{ dev_scripts_dir }}/ocp/auth/kubeadmin-password)

    source ./contrib/oc-environment.sh

    nohup bin/bridge &>/tmp/web-ui.log  &

  args:
    chdir: "{{ go_path }}/src/github.com/kubevirt/web-ui"
  async: 10
  poll: 0

- name: "Build yarn development server"
  command:
    yarn install
  args:
    chdir: "{{ go_path }}/src/github.com/kubevirt/web-ui/frontend"

- name: "Start yarn development server"
  command:
    nohup yarn run dev &>>/tmp/web-ui.log &
  args:
    chdir: "{{ go_path }}/src/github.com/kubevirt/web-ui"
  async: 10
  poll: 0

  
