- name: run 09_deploy_kubevirt.sh
#  hosts:  virthost
  shell: "{{ dev_scripts_dir }}/09_deploy_kubevirt.sh" 
  args:
    chdir: "{{ dev_scripts_dir }}"
    creates: "{{ dev_scripts_dir }}/logs/09_deploy_kubevirt*.log"
