# Create a non-root user on the target host.  This is the user that
# will own the virtual infrastructure on which we deploy openstack.
- name: Create non-root group
  group:
    name: "{{ rhhi_user }}"
    state: present
  become: true
  when: not chrooted|bool

- name: Create non-root user
  user:
    name: "{{ rhhi_user }}"
    group: "{{ rhhi_user }}"
    state: present
    shell: /bin/bash
    create_home: true
  become: true
  when: not chrooted|bool
