- name: Create "config_{{ rhhi_user }}" file
  template:
    src: config_.sh.j2
    dest: "{{ dev_scripts_dir }}/config_{{ rhhi_user }}.sh"



- name: run 01_install_requirements.sh
#  hosts:  virthost
  shell: "{{ dev_scripts_dir }}/01_install_requirements.sh" 
  args:
    chdir: "{{ dev_scripts_dir }}"
    creates: "{{ dev_scripts_dir }}/logs/01_install_requirements*.log"

