- name: "10_deploy_rook.sh"
  hosts:  localhost
  tasks:
  - name: "10_deploy_rook.sh"
    shell: "{{ dev_scripts_dir }}/10_deploy_rook.sh"
    args:
      chdir: "{{ dev_scripts_dir }}"
      creates: "{{ dev_scripts_dir }}/logs/10_deploy_rook*.log"
