---
- name: "Clean up any existing dev-scripts deployments"
  hosts: virthost
  tasks:
  - name: "Check to see if dev-scripts already exists"
    stat:
      path: "{{ dev_scripts_dir }}"
    register: dev_scripts_exists
  - name: "Run make clean"
    command:
      make clean
    args:
      chdir: "{{ dev_scripts_dir }}"
    when: dev_scripts_exists.stat.exists == True

  - name: "Delete old dev-scripts logs"
    stat:
      path: "{{ dev_scripts_dir }}"
    register: dev_scripts_exists
  - file: 
      path: "{{ dev_scripts_dir }}/logs"
      state: absent
    when: dev_scripts_exists.stat.exists == True
  tags:
  - clean

- name: "Shut down existing, conflicting bridges"
  hosts: virthost
  tasks:
# TODO(dtrainor): Clean this up; should probably be using hostvars to only check this once.  Also, find a better way
# of determining what "exists" means - deployed successfully?  running?  maybe query an API etc...?
  - name: "Check to see if dev-scripts already exists"
    stat:
      path: "{{ dev_scripts_dir }}"
    register: dev_scripts_exists
  - name: "Check to see of provisioning bridge exists"
    command: 
      ip link show provisioning
    register: provisioning_bridge_exists
    ignore_errors: true
  - name: "Shut down provisioning bridge, if it exists"
    become: true
    command: ip link set dev provisioning down
    when:
      - dev_scripts_exists.stat.exists == True
      - provisioning_bridge_exists == True
  - name: "Check to see of baremetal bridge exists"
    command: 
      ip link show baremetal
    register: baremetal_bridge_exists
    ignore_errors: true
  - name: "Shut down baremetal bridge, if it exists"
    command:  ip link set dev baremetal down
    become: true
    when:
      - dev_scripts_exists.stat.exists == True
      - baremetal_bridge_exists == True
  tags:
  - clean

- name: "Remove existing, conflicting bridges"
  hosts: virthost
  tasks:
# TODO(dtrainor): Clean this up; should probably be using hostvars to only check this once.  Also, find a better way
# of determining what "exists" means - deployed successfully?  running?  maybe query an API etc...?
  - name: "Check to see if dev-scripts already exists"
    stat:
      path: "{{ dev_scripts_dir }}"
    register: dev_scripts_exists
  - name: "Check to see of provisioning bridge exists"
    command:
      ip link show provisioning
    register: provisioning_bridge_exists
    ignore_errors: true
  - name: "Remove provisioning bridge, if it exists"
    become: true
    command: brctl delbr provisioning
    when:
      - dev_scripts_exists.stat.exists == True
      - provisioning_bridge_exists == True
  - name: "Check to see of baremetal bridge exists"
    command: ip link show baremetal
    register: baremetal_bridge_exists
    ignore_errors: true
  - name: "Remove baremetal bridge, if it exists"
    command:  brctl delbr baremetal
    become: true
    when:
      - dev_scripts_exists.stat.exists == True
      - baremetal_bridge_exists == True
  tags:
  - clean

- name: "Kill any existing web-ui bridge instances"
  hosts: virthost
  tasks:
  - name: "pkill bin/bridge instances"
    command:
      pkill bridge
    ignore_errors: true
  tags:
  - clean

