---
- name: "Install prerequisite packages"
  hosts: virthost
  tasks:
  - yum:
      name: "{{ packages }}"
  vars:
    packages:
      - git
      - gcc-c++
      - krb5-devel
  become: true
  tags:
    - provision
