- name: "Pull web-ui repo"
  hosts: virthost
  tasks:
  - git:
      repo:  https://github.com/kubevirt/web-ui.git
      dest:  "{{ go_path }}/src/github.com/kubevirt/web-ui"
      refspec: "{{ web_ui_refspec }}"
      version: "master"
      force: true
  tags:
    - web_ui
