- name: "Check to see if pull secret was defined"
  hosts: virthost
  tasks:
  - git:
      repo:  https://github.com/dantrainor/dev-scripts.git
      dest:  "/home/{{ rhhi_user }}/dev-scripts"
        
  tags:
    - provision 
